export type ImageRole =
  | "operacao"
  | "lideranca"
  | "territorio"
  | "impacto"
  | "educacao"
  | "evento"
  | "logistica"
  | "triagem"
  | "manifesto"
  | "regeneracao"
  | "tecnologia"
  | "dado"

export type ImageStatus =
  | "provisoria"
  | "acervo"
  | "validacao"
  | "banco"
  | "substituir"
  | "origem_pendente"

export interface InstitutionalImage {
  src: string
  alt: string
  srcSet?: string
  sizes?: string
  objectPosition?: string
  aspect?: string
  badge?: string
  loading?: 'lazy' | 'eager'
  section: string
  role: ImageRole
  status: ImageStatus
  width?: number
  height?: number
  weightKb?: number
  source?: string
  license?: string
  notes?: string
}

export const homeImages = {
  hero: {
    src: "/images/hero-reciclagem.jpg",
    alt: "Equipe atuando em operação de reciclagem e triagem de resíduos.",
    srcSet: "/images/hero-reciclagem-mobile.jpg 1200w, /images/hero-reciclagem.jpg 2200w",
    sizes: "(max-width: 767px) calc(100vw - 40px), (max-width: 1023px) calc(100vw - 64px), 599px",
    objectPosition: "56% 50%",
    aspect: "5 / 4",
    badge: "Imagem provisória",
    loading: "eager",
    section: "Hero",
    role: "operacao",
    status: "provisoria",
    width: 2200,
    height: 1650,
    weightKb: 674.9,
    source: "Arquivo fornecido pelo usuário",
    license: "Direitos de uso pendentes de validação",
    notes: "Imagem principal. Otimizada para reduzir peso sem alterar composição. Possui variante mobile de 1200x900 com 234.5 KB.",
  },
  aboutRobson: {
    src: "/images/robson-borges-robinho-liberdade.jpg",
    alt: "Robson Borges, Robinho Liberdade, liderança da Eu Quero Liberdade.",
    objectPosition: "50% 38%",
    aspect: "4 / 3",
    badge: "Imagem em validação",
    loading: "lazy",
    section: "Quem Somos",
    role: "lideranca",
    status: "validacao",
    width: 640,
    height: 640,
    weightKb: 43.2,
    source: "Arquivo fornecido pelo usuário",
    license: "Validar autorização de uso como acervo",
    notes: "Foto humana central da narrativa. Manter foco em rosto e tronco.",
  },
  purpose: {
    src: "/images/proposito-transformacao-residuos.jpg",
    alt: "Mão segurando material reciclável triturado em processo de transformação.",
    objectPosition: "56% 62%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Propósito",
    role: "regeneracao",
    status: "provisoria",
    width: 1347,
    height: 2400,
    weightKb: 324.2,
    source: "Arquivo fornecido pelo usuário",
    license: "Direitos de uso pendentes de validação",
    notes: "Imagem vertical. Usar recorte com foco na mão e material reciclável.",
  },
  process: {
    src: "/images/processo-triagem-residuos.jpg",
    alt: "Trabalho de separação e triagem de resíduos recicláveis.",
    objectPosition: "50% 48%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Como Trabalhamos",
    role: "triagem",
    status: "provisoria",
    width: 612,
    height: 408,
    weightKb: 57.8,
    source: "Arquivo fornecido pelo usuário",
    license: "Direitos de uso pendentes de validação",
    notes: "Baixa resolução para áreas muito grandes. Usar com cautela.",
  },
  impact: {
    src: "/images/impacto-trabalho-reciclagem.jpg",
    alt: "Trabalhadora em operação de reciclagem com vidro e materiais reaproveitáveis.",
    objectPosition: "70% 50%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Impacto",
    role: "impacto",
    status: "provisoria",
    width: 2200,
    height: 1467,
    weightKb: 357.9,
    source: "Arquivo fornecido pelo usuário",
    license: "Direitos de uso pendentes de validação",
    notes: "Boa imagem humana-operacional. Manter foco na trabalhadora.",
  },
  manifesto: {
    src: "/images/manifesto-logistica-reversa.jpg",
    alt: "Garrafas plásticas descartadas representando logística reversa e economia circular.",
    objectPosition: "50% 50%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Diferenciais",
    role: "manifesto",
    status: "provisoria",
    width: 2200,
    height: 1467,
    weightKb: 524.2,
    source: "Arquivo fornecido pelo usuário",
    license: "Direitos de uso pendentes de validação",
    notes: "Imagem em preto e branco com tom de manifesto. Não usar como prova de projeto executado.",
  },
  territory: {
    src: "/images/territorio-comunidade.jpg",
    alt: "Espaço comunitário colorido representando território, convivência e transformação social.",
    objectPosition: "50% 42%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Contato",
    role: "territorio",
    status: "provisoria",
    width: 1024,
    height: 683,
    weightKb: 193.1,
    source: "Arquivo fornecido pelo usuário",
    license: "Direitos de uso pendentes de validação",
    notes: "Imagem territorial forte, mas pode remeter a projeto cultural. Validar aderência com Robson.",
  },
  solutionEvents: {
    src: "/images/solucao-eventos-sustentaveis.jpg",
    alt: "Profissional de limpeza atuando em área de evento com resíduos espalhados no gramado.",
    objectPosition: "36% 55%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Soluções",
    role: "evento",
    status: "provisoria",
    width: 2200,
    height: 1467,
    weightKb: 305.5,
    source: "event waste management.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Imagem principal para solução de eventos sustentáveis. Não associar a evento executado sem validação.",
  },
  solutionCollection: {
    src: "/images/solucao-coleta-logistica.jpg",
    alt: "Trabalhadores carregando grande volume de garrafas plásticas para coleta e transporte.",
    objectPosition: "52% 62%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Soluções",
    role: "logistica",
    status: "provisoria",
    width: 1466,
    height: 2200,
    weightKb: 799.3,
    source: "waste collection.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Imagem forte para coleta e logística. Usar com recorte menor se também for usada futuramente no Hero.",
  },
  solutionSorting: {
    src: "/images/solucao-triagem-residuos.jpg",
    alt: "Trabalhadores em linha de triagem separando resíduos recicláveis.",
    objectPosition: "50% 50%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Soluções",
    role: "triagem",
    status: "provisoria",
    width: 960,
    height: 720,
    weightKb: 146.4,
    source: "trabalhadores de triagem de residuos.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Boa leitura operacional para triagem. Usar em área pequena ou média.",
  },
  solutionEducation: {
    src: "/images/solucao-educacao-ambiental.jpg",
    alt: "Crianças participando de atividade prática de educação ambiental e plantio.",
    objectPosition: "50% 52%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Soluções",
    role: "educacao",
    status: "provisoria",
    width: 678,
    height: 452,
    weightKb: 88.4,
    source: "environmental education.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Imagem principal para educação ambiental por mostrar atividade prática e coletiva.",
  },
  solutionConsulting: {
    src: "/images/solucao-consultoria-formacao.jpg",
    alt: "Palestra com público em auditório representando formação e consultoria socioambiental.",
    objectPosition: "50% 46%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Soluções",
    role: "educacao",
    status: "provisoria",
    width: 2200,
    height: 1467,
    weightKb: 496.8,
    source: "community workshop.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Usar apenas para consultoria, formação ou mobilização institucional.",
  },
  projectCommunityReuse: {
    src: "/images/projeto-comunidade-reuso.jpg",
    alt: "Pessoas em oficina comunitária pintando pneus para reaproveitamento em espaço coletivo.",
    objectPosition: "55% 58%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Projetos",
    role: "territorio",
    status: "provisoria",
    width: 2200,
    height: 1464,
    weightKb: 634.8,
    source: "community project.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Representa projeto comunitário e reaproveitamento. Tratar como ilustrativa até haver acervo próprio.",
  },
  projectEducationWorkshop: {
    src: "/images/projeto-educacao-ambiental.jpg",
    alt: "Crianças participando de oficina de reciclagem com materiais reaproveitáveis.",
    objectPosition: "48% 50%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Projetos",
    role: "educacao",
    status: "provisoria",
    width: 612,
    height: 500,
    weightKb: 53.7,
    source: "oficina de reciclagem.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Alternativa para projeto educacional quando a imagem de educação já estiver em Soluções.",
  },
  projectSustainableEvent: {
    src: "/images/projeto-evento-sustentavel.jpg",
    alt: "Tambores de coleta seletiva em evento com sinalização de recicláveis e orgânicos.",
    objectPosition: "50% 48%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Projetos",
    role: "evento",
    status: "provisoria",
    width: 676,
    height: 453,
    weightKb: 50.5,
    source: "eventos de reciclagem.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Usar com cautela por marcas de terceiros visíveis. Não apresentar como registro proprietário.",
  },
  projectTerritoryCommunity: {
    src: "/images/projeto-territorio-comunidade.jpg",
    alt: "Vista de comunidade urbana em morro com quadra e moradias.",
    objectPosition: "50% 48%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Projetos",
    role: "territorio",
    status: "provisoria",
    width: 1467,
    height: 2200,
    weightKb: 962,
    source: "favela.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Representa contexto territorial. Não tratar como projeto específico sem comprovação.",
  },
  problemUrbanWaste: {
    src: "/images/problema-residuo-urbano.jpg",
    alt: "Resíduos acumulados em área urbana representando descarte irregular.",
    objectPosition: "52% 58%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Como Trabalhamos",
    role: "manifesto",
    status: "provisoria",
    width: 1406,
    height: 1800,
    weightKb: 460.4,
    source: "urban waste.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Imagem negativa mais moderada para representar ponto de partida do problema. Evitar uso dominante.",
  },
  reservePurposeRegeneration: {
    src: "/images/reserva-proposito-regeneracao.jpg",
    alt: "Pessoa segurando uma muda de planta nas mãos.",
    objectPosition: "50% 50%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Reserva",
    role: "regeneracao",
    status: "provisoria",
    width: 1235,
    height: 2200,
    weightKb: 183.3,
    source: "pexels-ian-panelo-7538364.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Reserva simbólica para propósito. Não usar como prova operacional.",
  },
  reserveImpactCooperativeWork: {
    src: "/images/reserva-impacto-trabalho-cooperativo.jpg",
    alt: "Trabalhadora sorrindo durante separação de materiais recicláveis.",
    objectPosition: "58% 50%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Reserva",
    role: "impacto",
    status: "provisoria",
    width: 678,
    height: 452,
    weightKb: 105.2,
    source: "trabalhadores coperativos.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Imagem humana forte para impacto social. Não associar a números ou depoimentos específicos.",
  },
  reserveImpactRecyclingAgent: {
    src: "/images/reserva-impacto-agente-reciclagem.jpg",
    alt: "Agente de reciclagem manuseando sacos com garrafas plásticas.",
    objectPosition: "47% 56%",
    aspect: "4 / 3",
    badge: "Imagem provisória",
    loading: "lazy",
    section: "Reserva",
    role: "logistica",
    status: "provisoria",
    width: 1467,
    height: 2200,
    weightKb: 358.5,
    source: "agentes de reciclagem.jpg",
    license: "Direitos de uso pendentes de validação",
    notes: "Reserva para trabalho de campo e valorização dos materiais.",
  },
} as const satisfies Record<string, InstitutionalImage>
